title: Lenovo HPC
email: hpchelp@lenovo.com
description: >
  Lenovo HPC resources, news, and documentation
baseurl: /VERSION
markdown: kramdown

kramdown:
        input: GFM
        hard_wrap: false
        syntax_highlighter: none

