name: ci 
on:
  push:
    branches:
      - master
      - main
      - mkdocs
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: Install Material for MkDocs requirements
        run: pip install mkdocs-material mkdocs-git-revision-date-localized-plugin
      - name: Install Ronn dependency
        run: sudo apt-get install -y ronn
      - uses: actions/checkout@v4
        with:
          name: xcat2/confluent
      - name: Generate nodeattrib document
        run: ./makeattribdoc
      - name: Generate man pages
        run: ./makeman
      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
