name: ci 
on:
  push:
    branches:
      - master
      - main
      - mkdocs
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: Install Material for MkDocs requirements
        run: pip install mkdocs-material mkdocs-git-revision-date-localized-plugin
      - name: Install Ronn for man pages
        run: sudo apt-get install -y ronn
      - name: Checkout confluent repository for nodeattrib and man pages
        uses: actions/checkout@v4
        with:
          repository: xcat2/confluent
          path: confluent
          sparse-checkout: |
            confluent/confluent_server/confluent/config/attributes.py
            confluent/confluent_client/addattribs.py
            confluent/confluent_client/doc/man
      - name: Make nodeattrib document
        run: python3 makeattribdoc
      - name: Make man pages
        run: bash makeman
      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
